export interface Inscriptos {
    id: number,
    fecha:Date,
    ci:string,
    corredor:string,
    sexo:number,
    fecnac:Date,
    telefono:string,
    ciudad: string,
    pais: string,
    club:string,
    categoria:string,
    codigo:string,
    km: number,
    acobrar:number,
    pagado: number,
    dorsal: number,
    nrogiro:string,
    chip:string,
    sex:string
}