export interface Inscripto {
    id: number,
    fecha:Date,
    ci:string,
    corredor:string,
    sexo:number,
    fecnac:Date,
    telefono:string,
    ciudad: string,
    pais: string,
    club:string,
    categoria:string,
    codigo:string,
    km: number,
    acobrar:number,
    pagado: number,
    dorsal: number,
    nrogiro:string,
    chip:string,
    tanda:number,
    orden:number,
    horario:string,
    tandac:string,
    sex:string,
    pag:string,
    kit:number,
    kittipo:string,
    tamano:number,
    tamanoc:string,
    logoclub:string,
    logoevento:string
    
}